import client from './weaviateClient'

const noteSchema = {
  class: 'Note',
  description: 'A note transcribed from a user\'s voice',
  vectorizer: 'text2vec-google',
  vectorizeProperties: true,
  moduleConfig: {
    'text2vec-google': {
      model: 'gemini-embedding-001',
      type: 'text',
    },
  },
  properties: [
    {
      name: 'transcript',
      dataType: ['text'],
      description: 'The final text content of the note'
    },
    {
      name: 'summary',
      dataType: ['text'],
      description: 'A concise summary of the note generated by AI'
    },
    {
      name: 'tags',
      dataType: ['text[]'],
      description: 'Relevant tags/categories for the note, suggested by AI'
    },
    {
      name: 'userId',
      dataType: ['text'],
      description: 'The ID of the user from Clerk who created this note'
    },
    {
      name: 'createdAt',
      dataType: ['date'],
      description: 'The timestamp when the note was created'
    }
  ]
}

async function setupWeaviate() {
  try {
    console.log('Connecting to Weaviate...')
    
    // Check if the Note class already exists
    const schema = await client.schema.getter().do()
    const existingClass = schema.classes?.find((cls: any) => cls.class === 'Note')
    
    if (existingClass) {
      console.log('Note class already exists, skipping creation.')
      return
    }
    
    // Create the Note class
    console.log('Creating Note class...')
    await client.schema.classCreator().withClass(noteSchema).do()
    
    console.log('✅ Weaviate schema setup completed successfully!')
  } catch (error) {
    console.error('❌ Error setting up Weaviate schema:', error)
    process.exit(1)
  }
}

setupWeaviate()